service: task-api

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    IS_OFFLINE: true
    TABLE_NAME: tasks
    NODE_OPTIONS: --enable-source-maps
  logRetentionInDays: 14

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: GET
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: tasks
          method: ANY
          cors: true
      - http:
          path: tasks/{id}
          method: ANY
          cors: true

resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tasks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-plugin-include-dependencies
  - serverless-offline
  - serverless-dynamodb-local