service: task-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGO_URI: ${env:MONGO_URI}
    NODE_OPTIONS: --enable-source-maps
  logRetentionInDays: 14

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: GET
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            methods:
              - GET
              - POST
              - PUT
              - DELETE
      - http:
          path: tasks
          method: GET
          cors: true
      - http:
          path: tasks
          method: POST
          cors: true
      - http:
          path: tasks/{id}
          method: GET
          cors: true
      - http:
          path: tasks/{id}
          method: PUT
          cors: true
      - http:
          path: tasks/{id}
          method: DELETE
          cors: true
      - http:
          path: api-docs
          method: GET
          cors: true
      - http:
          path: swagger.yml
          method: GET
          cors: true

custom:
  serverless-offline:
    httpPort: 5000

plugins:
  - serverless-plugin-include-dependencies
  - serverless-offline

package:
  patterns:
    - 'swagger.yml'
    - '!node_modules/**'
    - 'node_modules/**'
